- name: install packages needed by iRODS
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-psutil
    - python-jsonschema
    - unixodbc
    - odbc-postgresql
    - postgresql-client
    - super
    - libfuse2
    - libjson-perl
    - lsof
  when: ansible_os_family == "Debian"

- name: create irods user
  user: name={{ IRODS_SERVICE_ACCOUNT }} password={{ ENC_PASSWORD }} update_password=always shell=/bin/bash home=/home/{{ IRODS_SERVICE_ACCOUNT }} groups=sudo append=yes

- name: download irods
  get_url: url={{ IRODSFTP }}/releases/{{ IRODSVERSION }}/ubuntu14/{{ item }} dest=/tmp
  with_items:
    - irods-icat-{{ IRODSVERSION }}-ubuntu14-x86_64.deb
    - irods-database-plugin-postgres-{{ IRODSPLUGINSVERSION }}-ubuntu14-x86_64.deb

- name: install irods packages
  shell: dpkg -iE *.deb
  args:
    chdir: /tmp/

- name: remove pkgs
  command: rm -f /tmp/*.deb

- name: copy irods install script
  template: src=install.sh.j2 dest=/install mode=0755

- name: copy answers
  template: src=answers.sh.j2 dest={{ ANSWERS_SCRIPT_PATH }} mode=0755

- name: create answers
  command: "{{ ANSWERS_SCRIPT_PATH }} {{ ANSWERS_PATH }}"

