- name: install packages needed by iRODS
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-psutil
    - python-jsonschema
    - unixodbc
    - odbc-postgresql
    - postgresql-client
    - super
    - libfuse2
    - libjson-perl
    - lsof
  when: ansible_os_family == "Debian"

- name: create irods user
  user: name={{ IRODS_SERVICE_ACCOUNT }} password={{ ENC_PASSWORD }} update_password=always shell=/bin/bash home=/home/{{ IRODS_SERVICE_ACCOUNT }} groups=sudo append=yes

- name: copy irods user sudoers config
  template: src=sudoers.j2 dest=/etc/sudoers.d/irods mode=0440

- name: download irods packages
  get_url: url={{ IRODSFTP }}/releases/{{ IRODSVERSION }}/ubuntu14/{{ item }} dest=/tmp
  with_items:
    - irods-icat-{{ IRODSVERSION }}-ubuntu14-x86_64.deb
    - irods-database-plugin-postgres-{{ IRODSPLUGINSVERSION }}-ubuntu14-x86_64.deb

- name: install irods packages
  shell: dpkg -iE *.deb
  args:
    chdir: /tmp/

- name: remove irods packages
  file: path=/tmp/{{ item }} state=absent
  with_items:
    - irods-icat-{{ IRODSVERSION }}-ubuntu14-x86_64.deb
    - irods-database-plugin-postgres-{{ IRODSPLUGINSVERSION }}-ubuntu14-x86_64.deb

- name: copy irods config script
  template: src=config.sh.j2 dest=/irods_config mode=0755

- name: copy irods setup script
  template: src=setup.sh.j2 dest=/irods_setup mode=0755

- name: copy answers
  template: src=answers.sh.j2 dest={{ ANSWERS_SCRIPT_PATH }} mode=0755

- name: create answers
  command: "{{ ANSWERS_SCRIPT_PATH }} {{ ANSWERS_PATH }}"

