- name: install packages needed by iRODS
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - python-psutil
    - python-jsonschema
    - unixodbc
    - odbc-postgresql
    - postgresql-client
    - super
    - libfuse2
    - libjson-perl
    - lsof
  when: ansible_os_family == "Debian"

- name: create irods user
  user: name={{ IRODS_SERVICE_ACCOUNT }} password={{ ENC_PASSWORD }} update_password=always shell=/bin/bash home=/home/{{ IRODS_SERVICE_ACCOUNT }} groups=sudo append=yes

- name: set env variable to force hostname
  lineinfile: dest=/home/irods/.profile line="export LOCAL_HOST_NAME={{ IRODSHOSTNAME }}"
  when: ansible_virtualization_type == "docker"

- name: download irods
  get_url: url={{ IRODSFTP }}/releases/{{ IRODSVERSION }}/ubuntu14/{{ item }} dest=/tmp
  with_items:
    - irods-icat-{{ IRODSVERSION }}-ubuntu14-x86_64.deb
    - irods-database-plugin-postgres-{{ IRODSPLUGINSVERSION }}-ubuntu14-x86_64.deb

- name: install irods packages
  shell: dpkg -iE *.deb
  args:
    chdir: /tmp/

- name: copy answers
  template: src=answers.sh.j2 dest=/tmp/answers.sh mode=0755

- name: create answers
  command: /tmp/answers.sh /tmp/answers

- name: configure irods
  shell: /var/lib/irods/packaging/setup_irods.sh < /tmp/answers