- name: install packages needed by icommands
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - libfuse2
  when: ansible_os_family == "Debian"

- name: create irods user
  user: name={{ IUSER }} password={{ ENC_PASSWORD }} update_password=always shell=/bin/bash home=/home/{{ IUSER }} groups=sudo append=yes

- name: download icommands
  get_url: url={{ IRODSFTP }}/releases/{{ IRODSVERSION }}/ubuntu14/{{ item }} dest=/tmp
  with_items:
    - irods-icommands-{{ IRODSVERSION }}-ubuntu14-x86_64.deb

- name: install irods packages
  shell: dpkg -iE *.deb
  args:
    chdir: /tmp/

- name: remove pkgs
  file: path=/tmp/*.deb state=absent
