version: '2'
services:
  icommands:
    build: ./icommands
    image: gmauro/icommands
    hostname: icommands
    container_name: icommands
    volumes:
        - icommands_home:/home
    links:
        - irods:irodserver
  irods:
    build: ./icat
    image: gmauro/boxed-irods
    hostname: irodserver
    container_name: boxed-irods
    ports:
        - 1247:1247
    volumes:
        - boxed-irods_etc:/etc
        - boxed-irods_home:/home
        - boxed-irods_var:/var/lib

volumes:
   icommands_home:
     driver: local
   boxed-irods_etc:
     driver: local
   boxed-irods_home:
     driver: local
   boxed-irods_var:
     driver: local
